### ISSUE TITLE
Refactoring Tensorflow code

### ISSUE THREAD

**Issue by felix-hilden** [jjdabr/forecastNet#5]
Hello, thank you for providing the code of your research!

I would like to help improve the code style of this repository, as it contains lots of unnecessarily duplicated code and suboptimal formatting. I've started the work on my fork, from which I'll shoot a pull request. But I wanted to make sure we're on the same page first. I see different types of issues.
- Minor formatting issues (spacing, line length, commented code)
- Style issues (duplication, argument and variable names)
- Opinionated changes (function names and module structure, removing the paper information from each individual file and so on)

I think the formatting style issues should be fixed, but making the opinionated changes would be your call as the author. What do you think? I can make a different PR for the opinionated stuff too, if you'd like to review them separately.

**Comment by jjdabr** [comment]
Thank you very much for your interest. 

I highly recommend that you use the PyTorch code rather than the TensorFlow code. The TensorFlow contains some test code of an early draft of the model. I have updated the markdown files with more information on this. If you prefer not to use PyTorch, you are welcome to reformat the TensorFlow code in your fork as you wish. If you do, I highly recommend having a look at the PyTorch code anyway for hints on making the code more generic. You should also find better formatting and naming in the PyTorch code.

**Comment by felix-hilden** [comment]
Thanks for the response, I think I'll try out PyTorch then. If I do decide to change the TF code according to PyTorch, is a PR welcome at all?

**Comment by jjdabr** [comment]
You are more than welcome to make comments and I will try address them (though, I do not intend to improve the TensorFlow code). Also, I do not intend to have multiple maintainers of the code as this is not a "project". The idea is more that anyone is welcome to download the code and modify it for their purposes.
